include(CMakeFindDependencyMacro)
if (DEFINED USE_SDL2)
    find_dependency(SDL2)
else()
    find_dependency(SDL3)
endif ()
find_dependency(EnTT)
include("${CMAKE_CURRENT_LIST_DIR}/ion-mylar-targets.cmake")
add_library(ion::mylar ALIAS ion::ion-mylar)
