include(CMakeFindDependencyMacro)
find_dependency(SDL3)
find_dependency(EnTT)
find_dependency(GLEW)
find_dependency(yaml-cpp)
find_dependency(ion-konbu)
find_dependency(ion-photon)
include("${CMAKE_CURRENT_LIST_DIR}/ion-engine-targets.cmake")
