[munchable]
colors = [[ 0xf3, 0x91, 0x89 ],
          [ 0xbb, 0x80, 0x82 ],
          [ 0x62, 0x75, 0x82 ],
          [ 0x04, 0x65, 0x82 ]]
minspeed = 100.0
maxspeed = 200.0
angle_variation = 0.5236
size_variation = 0.8
spawn_likelihood = 0.01

[player]
color = [ 0x0, 0x0, 0x0 ]
size = 15.0
acceleration = 200.0
friction = 100.0
minspeed = 0.1
maxspeed = 160.0
growth_rate = 0.06
